language: python
matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.6
    - os: osx
      language: generic
      env: PYTHON=2.7.10
    - os: osx
      language: generic
      env: PYTHON=3.6.6
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then 
    brew update
    brew install pyenv-virtualenv
    pyenv install "$PYTHON"
    eval "$(pyenv init -)"
    pyenv virtualenv "$PYTHON" venv
    pyenv activate venv
  fi
install:
  - pip install pipenv --upgrade
  - pipenv install --dev --skip-lock
script:
  - pipenv run py.test tests/tests.py

